import { existsSync, mkdirSync, copyFileSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { Plugin } from "vite";

/**
 * Serves the /data artefacts the app fetches from its own origin.
 *
 * Two sources, deliberately not interchangeable:
 *
 * - programs/* and external-credit-rules.json are HAND-WRITTEN and committed, so
 *   they always come from the repository.
 * - manifest, catalog, sections and offering history are GENERATED by the
 *   nightly pipeline. Until that lands they come from apps/web/dev-fixtures,
 *   and the app is told so, so the UI can shout about it.
 *
 * A production build never falls back: shipping fixture data as though it were
 * the catalog is the one failure this whole product cannot survive.
 */

const GENERATED = ["manifest.json", "catalog.json", "offering-history.json"];
const COMMITTED = ["external-credit-rules.json"];

export type ServeDataOptions = { repoRoot: string; webRoot: string };

export function hasRealData(repoRoot: string): boolean {
  return existsSync(join(repoRoot, "data", "manifest.json"));
}

export function serveData({ repoRoot, webRoot }: ServeDataOptions): Plugin {
  const repoData = join(repoRoot, "data");
  const fixtures = join(webRoot, "dev-fixtures");
  const real = hasRealData(repoRoot);
  const generatedRoot = real ? repoData : fixtures;

  return {
    name: "sageplan-serve-data",

    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? "").split("?")[0] ?? "";
        if (!url.startsWith("/data/")) return next();

        const rel = url.slice("/data/".length);
        if (rel.includes("..")) {
          res.statusCode = 400;
          res.end("bad path");
          return;
        }

        const file = resolveArtefact(rel, repoData, generatedRoot);
        if (!file || !existsSync(file)) {
          res.statusCode = 404;
          res.setHeader("content-type", "application/json");
          res.end(JSON.stringify({ error: `no artefact at /data/${rel}` }));
          return;
        }

        res.setHeader("content-type", "application/json");
        res.setHeader("cache-control", "no-store");
        res.end(readFileSync(file));
      });
    },

    closeBundle() {
      // Build time: fixtures must never ship.
      if (!real) {
        throw new Error(
          "Refusing to build: data/manifest.json is missing, so only dev fixtures are available. " +
            "Run the pipeline (npm run pipeline:all) before building. Fixture data must never ship as the catalog.",
        );
      }
      const out = join(webRoot, "dist", "data");
      mkdirSync(join(out, "programs"), { recursive: true });
      for (const name of [...GENERATED, ...COMMITTED]) {
        const from = join(repoData, name);
        if (existsSync(from)) copyFileSync(from, join(out, name));
      }
      for (const name of readdirSync(repoData).filter((f) => f.startsWith("sections-") && f.endsWith(".json"))) {
        copyFileSync(join(repoData, name), join(out, name));
      }
      const programs = join(repoData, "programs");
      if (existsSync(programs)) {
        for (const name of readdirSync(programs).filter((f) => f.endsWith(".json"))) {
          copyFileSync(join(programs, name), join(out, "programs", name));
        }
      }
    },
  };
}

/** programs/* and the rules file are always real; the rest may be fixtures. */
function resolveArtefact(rel: string, repoData: string, generatedRoot: string): string | null {
  if (rel.startsWith("programs/") || COMMITTED.includes(rel)) {
    return join(repoData, ...rel.split("/"));
  }
  if (GENERATED.includes(rel) || (rel.startsWith("sections-") && rel.endsWith(".json"))) {
    return join(generatedRoot, rel);
  }
  return null;
}
