import { z } from "zod";
import { CatalogYearSchema, CourseIdSchema, GeAttributeSchema, TermIdSchema } from "./ids.ts";
import { RuleSchema } from "./rule.ts";

/** Generated by the pipeline. Read-only to the app. */

export const CourseSchema = z
  .object({
    id: CourseIdSchema,
    title: z.string().min(1),
    description: z.string(),
    department: z.string().describe('Offering department name as Coursedog reports it, e.g. "Computer Science".'),
    credits: z.object({
      min: z.number().min(0),
      max: z.number().min(0),
      repeatable: z.boolean(),
      maxRepeats: z.number().int().min(0),
    }).describe("Structured credit value. Handles 0.25 PE and 0.5 half-courses."),
    attributes: z.array(GeAttributeSchema).describe("GE attributes the Registrar tagged. Already reflects the catalog's eligibility exclusions; the engine adds no exclusion logic."),
    gradeMode: z.string(),
    prereqText: z.string().nullable().describe("Verbatim prose. Display only. Never parsed for enforcement."),
    prereqRule: RuleSchema.nullable().describe("Only the ~5% of courses with structured requisites. Advisory only."),
    catalogYear: CatalogYearSchema,
    sourceUrl: z.url(),
    lastVerified: z.iso.datetime(),
  })
  .meta({ id: "Course" });
export type Course = z.infer<typeof CourseSchema>;

export const MeetingSchema = z
  .object({
    days: z.array(z.string()).describe('Day letters as Hyperschedule reports them, e.g. ["M","W"].'),
    startSec: z.number().int().min(0).describe("Seconds after midnight."),
    endSec: z.number().int().min(0),
    location: z.string(),
  })
  .meta({ id: "Meeting" });
export type Meeting = z.infer<typeof MeetingSchema>;

export const SectionSchema = z
  .object({
    course: CourseIdSchema,
    sectionNumber: z.number().int().min(0),
    term: TermIdSchema,
    half: z.string().nullable().describe('"F"/"S" for half-semester sections, else null.'),
    instructors: z.array(z.string()),
    meetings: z.array(MeetingSchema),
    seatsTotal: z.number().int().min(0),
    seatsFilled: z.number().int().min(0),
    permCount: z.number().int().min(0),
    status: z.string().describe('Hyperschedule status, e.g. "open", "closed", "reopened".'),
    geCodes: z.array(z.string()).describe('Raw Hyperschedule course-area codes for this section, e.g. ["1A3","1ADR"]. Pipeline cross-checks these against catalog attributes.'),
  })
  .meta({ id: "Section" });
export type Section = z.infer<typeof SectionSchema>;

export const OfferingHistorySchema = z
  .object({
    course: CourseIdSchema,
    terms: z.array(TermIdSchema).describe("Every term the course has been offered, ascending, back to ~2012."),
  })
  .meta({ id: "OfferingHistory" });
export type OfferingHistory = z.infer<typeof OfferingHistorySchema>;
