#!/usr/bin/env bash
# Regenerate docs/tasks/INDEX.md from the frontmatter of docs/tasks/*.md
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
python3 - <<'PY'
import glob,os,re
# Round comes from the reviewer-owned ledger (ADR-019), not from task frontmatter:
# the reviewer increments it on a branch that used to never reach main, so the
# frontmatter counter was always stale. Frontmatter is the fallback when the
# ledger has no row yet.
ledger={}
try:
    for ln in open('docs/review/rounds.md',encoding='utf-8',errors='ignore'):
        m=re.match(r'\|\s*(TASK-\d+)\s*\|\s*(\d+)\s*\|\s*([A-Z_-]+)\s*\|', ln)
        if m:
            tid,rnd,verdict=m.group(1),int(m.group(2)),m.group(3)
            if rnd >= ledger.get(tid,(0,''))[0]: ledger[tid]=(rnd,verdict)
except FileNotFoundError:
    pass
dupes=[]
# Ledger shape guards. These files are merge=union because they are append-only,
# which is true of their CONTENT and false the moment their SCHEMA changes: a new
# column produces a second header and a duplicated table that parses fine and is
# silently wrong. Loop control reads rounds.md, so that silence is expensive.
# ADR-024.
ledger_problems=[]
def _check_ledger(path, idcol):
    # Guards the INVARIANT (ids are unique; a row matches its own table's header),
    # never the FORMATTING. An earlier version treated "more than one header row"
    # as corruption, which made a deliberately sectioned ledger indistinguishable
    # from a damaged one and turned CI red on a clean file. That was the guard
    # becoming a premise about a file's shape - the exact failure ADR-024 was
    # written to name. Sections are legitimate; duplicate ids are not.
    probs=[]
    try: lines=open(path,encoding='utf-8',errors='ignore').read().splitlines()
    except FileNotFoundError: return probs
    heads=[i for i,l in enumerate(lines) if re.match(r'^\|\s*'+idcol+r'\s*\|', l)]
    ncol=0; seen={}
    for i,l in enumerate(lines):
        if i in heads: ncol=l.count('|'); continue      # a new section resets the shape
        m=re.match(r'^\|\s*((?:TASK|D)-\d+)\s*\|\s*(\d*)', l)
        if not m: continue
        if ncol and l.count('|')!=ncol:
            probs.append(f"{path}:{i+1}: {l.count('|')-1} columns, its table's header has {ncol-1}")
        key=(m.group(1), m.group(2))
        if key in seen:
            probs.append(f"{path}:{i+1}: duplicate row for {m.group(1)}"
                         + (f" round {m.group(2)}" if m.group(2) else "")
                         + f" (first at line {seen[key]+1})")
        else: seen[key]=i
    if probs and len(heads)>1:
        probs.append(f"{path}: {len(heads)} header rows (lines {', '.join(str(h+1) for h in heads)}) - if these are not deliberate sections, a union merge appended a table")
    return probs
ledger_problems += _check_ledger('docs/review/rounds.md','Task')
ledger_problems += _check_ledger('docs/DEBT.md','ID')
rows=[]
for p in sorted(glob.glob('docs/tasks/*.md')):
    b=os.path.basename(p)
    if b in ('INDEX.md','TASK-000-template.md'): continue
    t=open(p,encoding='utf-8',errors='ignore').read()
    m=re.match(r'^---\n(.*?)\n---', t, re.S)
    if not m:
        print(f"WARN {p}: no frontmatter, skipped"); continue
    pairs=re.findall(r'^([a-z_]+):\s*(.*)$', m.group(1), re.M)
    seen={}
    for k,v in pairs:
        if k in seen and seen[k]!=v: dupes.append(f"{b}: '{k}' appears twice ({seen[k]!r} and {v!r})")
        seen[k]=v
    fm=dict(pairs)
    tid=fm.get('id','?')
    rnd,verdict=ledger.get(tid,(None,''))
    rnd=str(rnd if rnd is not None else fm.get('round','0'))
    rows.append((tid, fm.get('status','?'), fm.get('owner','?'),
                 rnd, fm.get('title','?'), fm.get('blocked_on','').strip('"'), verdict))
order={'BLOCKED':0,'REVIEW':1,'IN_PROGRESS':2,'READY':3,'BACKLOG':4,'DONE':5}
rows.sort(key=lambda r:(order.get(r[1],9), r[0]))
out=["# Task Index","",
     "Generated by `scripts/tasks.sh` from the frontmatter of `docs/tasks/*.md`.",
     "Do not edit by hand — edit the task files and regenerate.","",
     "| ID | Status | Owner | Round | Last verdict | Title |","|---|---|---|---|---|---|"]
for i,s,o,r,ti,bo,v in rows:
    ti = f"{ti} _(blocked on: {bo})_" if s=='BLOCKED' and bo else ti
    out.append(f"| {i} | {s} | {o} | {r} | {v or '—'} | {ti} |")
if not rows: out.append("| — | — | — | — | _no tasks yet_ |")
counts={}
for r in rows: counts[r[1]]=counts.get(r[1],0)+1
out += ["", "**Counts:** " + (", ".join(f"{k} {v}" for k,v in sorted(counts.items())) or "none")]
open('docs/tasks/INDEX.md','w').write("\n".join(out)+"\n")
print(f"docs/tasks/INDEX.md regenerated — {len(rows)} task(s)")
for i,s,o,r,ti,bo,v in rows:
    if s in ('BLOCKED','REVIEW') or int(r or 0)>=3: print(f"  ATTENTION {i} {s} round={r} {ti[:40]}")
if ledger_problems:
    print("\nLEDGER SHAPE PROBLEM (ADR-024) - these files are machine-read:")
    for d in ledger_problems: print("  "+d)
    print("  A union merge combines rows without reconciling them, so a schema change")
    print("  duplicates the whole table and still parses. Repair by hand; the owning")
    print("  role is the reviewer for both docs/review/rounds.md and docs/DEBT.md.")
if dupes:
    print("\nDUPLICATE FRONTMATTER KEYS — a union merge combined two writers (ADR-021):")
    for d in dupes: print("  "+d)
    print("  Fix the file by hand. One field, one owner: status is the worker's, round and")
    print("  verdict are the reviewer's in docs/review/rounds.md, the rest are the manager's.")
if dupes or ledger_problems:
    raise SystemExit(1)
PY
