#!/usr/bin/env bash
# Regenerate docs/tasks/INDEX.md from the frontmatter of docs/tasks/*.md
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
python3 - <<'PY'
import glob,os,re
# Round comes from the reviewer-owned ledger (ADR-019), not from task frontmatter:
# the reviewer increments it on a branch that used to never reach main, so the
# frontmatter counter was always stale. Frontmatter is the fallback when the
# ledger has no row yet.
ledger={}
try:
    for ln in open('docs/review/rounds.md',encoding='utf-8',errors='ignore'):
        m=re.match(r'\|\s*(TASK-\d+)\s*\|\s*(\d+)\s*\|\s*([A-Z_-]+)\s*\|', ln)
        if m:
            tid,rnd,verdict=m.group(1),int(m.group(2)),m.group(3)
            if rnd >= ledger.get(tid,(0,''))[0]: ledger[tid]=(rnd,verdict)
except FileNotFoundError:
    pass
dupes=[]
rows=[]
for p in sorted(glob.glob('docs/tasks/*.md')):
    b=os.path.basename(p)
    if b in ('INDEX.md','TASK-000-template.md'): continue
    t=open(p,encoding='utf-8',errors='ignore').read()
    m=re.match(r'^---\n(.*?)\n---', t, re.S)
    if not m:
        print(f"WARN {p}: no frontmatter, skipped"); continue
    pairs=re.findall(r'^([a-z_]+):\s*(.*)$', m.group(1), re.M)
    seen={}
    for k,v in pairs:
        if k in seen and seen[k]!=v: dupes.append(f"{b}: '{k}' appears twice ({seen[k]!r} and {v!r})")
        seen[k]=v
    fm=dict(pairs)
    tid=fm.get('id','?')
    rnd,verdict=ledger.get(tid,(None,''))
    rnd=str(rnd if rnd is not None else fm.get('round','0'))
    rows.append((tid, fm.get('status','?'), fm.get('owner','?'),
                 rnd, fm.get('title','?'), fm.get('blocked_on','').strip('"'), verdict))
order={'BLOCKED':0,'REVIEW':1,'IN_PROGRESS':2,'READY':3,'BACKLOG':4,'DONE':5}
rows.sort(key=lambda r:(order.get(r[1],9), r[0]))
out=["# Task Index","",
     "Generated by `scripts/tasks.sh` from the frontmatter of `docs/tasks/*.md`.",
     "Do not edit by hand — edit the task files and regenerate.","",
     "| ID | Status | Owner | Round | Last verdict | Title |","|---|---|---|---|---|---|"]
for i,s,o,r,ti,bo,v in rows:
    ti = f"{ti} _(blocked on: {bo})_" if s=='BLOCKED' and bo else ti
    out.append(f"| {i} | {s} | {o} | {r} | {v or '—'} | {ti} |")
if not rows: out.append("| — | — | — | — | _no tasks yet_ |")
counts={}
for r in rows: counts[r[1]]=counts.get(r[1],0)+1
out += ["", "**Counts:** " + (", ".join(f"{k} {v}" for k,v in sorted(counts.items())) or "none")]
open('docs/tasks/INDEX.md','w').write("\n".join(out)+"\n")
print(f"docs/tasks/INDEX.md regenerated — {len(rows)} task(s)")
for i,s,o,r,ti,bo,v in rows:
    if s in ('BLOCKED','REVIEW') or int(r or 0)>=3: print(f"  ATTENTION {i} {s} round={r} {ti[:40]}")
if dupes:
    print("\nDUPLICATE FRONTMATTER KEYS — a union merge combined two writers (ADR-021):")
    for d in dupes: print("  "+d)
    print("  Fix the file by hand. One field, one owner: status is the worker's, round and")
    print("  verdict are the reviewer's in docs/review/rounds.md, the rest are the manager's.")
    raise SystemExit(1)
PY
