#!/usr/bin/env bash
# Regenerate docs/tasks/INDEX.md from the frontmatter of docs/tasks/*.md
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
python3 - <<'PY'
import glob,os,re
# Round comes from the reviewer-owned ledger (ADR-019), not from task frontmatter:
# the reviewer increments it on a branch that used to never reach main, so the
# frontmatter counter was always stale. Frontmatter is the fallback when the
# ledger has no row yet.
ledger={}
try:
    for ln in open('docs/review/rounds.md',encoding='utf-8',errors='ignore'):
        m=re.match(r'\|\s*(TASK-\d+)\s*\|\s*(\d+)\s*\|', ln)
        if m: ledger[m.group(1)]=max(int(m.group(2)), ledger.get(m.group(1),0))
except FileNotFoundError:
    pass
rows=[]
for p in sorted(glob.glob('docs/tasks/*.md')):
    b=os.path.basename(p)
    if b in ('INDEX.md','TASK-000-template.md'): continue
    t=open(p,encoding='utf-8',errors='ignore').read()
    m=re.match(r'^---\n(.*?)\n---', t, re.S)
    if not m:
        print(f"WARN {p}: no frontmatter, skipped"); continue
    fm=dict(re.findall(r'^([a-z_]+):\s*(.*)$', m.group(1), re.M))
    tid=fm.get('id','?')
    rnd=str(ledger.get(tid, fm.get('round','0')))
    rows.append((tid, fm.get('status','?'), fm.get('owner','?'),
                 rnd, fm.get('title','?'), fm.get('blocked_on','').strip('"')))
order={'BLOCKED':0,'REVIEW':1,'IN_PROGRESS':2,'READY':3,'BACKLOG':4,'DONE':5}
rows.sort(key=lambda r:(order.get(r[1],9), r[0]))
out=["# Task Index","",
     "Generated by `scripts/tasks.sh` from the frontmatter of `docs/tasks/*.md`.",
     "Do not edit by hand — edit the task files and regenerate.","",
     "| ID | Status | Owner | Round | Title |","|---|---|---|---|---|"]
for i,s,o,r,ti,bo in rows:
    ti = f"{ti} _(blocked on: {bo})_" if s=='BLOCKED' and bo else ti
    out.append(f"| {i} | {s} | {o} | {r} | {ti} |")
if not rows: out.append("| — | — | — | — | _no tasks yet_ |")
counts={}
for r in rows: counts[r[1]]=counts.get(r[1],0)+1
out += ["", "**Counts:** " + (", ".join(f"{k} {v}" for k,v in sorted(counts.items())) or "none")]
open('docs/tasks/INDEX.md','w').write("\n".join(out)+"\n")
print(f"docs/tasks/INDEX.md regenerated — {len(rows)} task(s)")
for i,s,o,r,ti,bo in rows:
    if s in ('BLOCKED','REVIEW') or int(r or 0)>=3: print(f"  ATTENTION {i} {s} round={r} {ti[:40]}")
PY
