/**
 * Generates docs/openapi.yaml from the zod schemas. The YAML is the committed,
 * human-readable twin; the schemas are authoritative. `--check` exits 1 when
 * the committed file is stale (CI runs this).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { stringify } from "yaml";
import { z } from "zod";
import { ARTEFACT_PATHS, SCHEMAS } from "../src/index.ts";

const here = fileURLToPath(new URL(".", import.meta.url));
const OUT = resolve(here, "../../../docs/openapi.yaml");

export function buildOpenApi(): Record<string, unknown> {
  // Registry mode: every named schema becomes a component and cross-references become $refs.
  const registry = z.registry<{ id: string }>();
  for (const [name, schema] of Object.entries(SCHEMAS)) registry.add(schema, { id: name });
  const emitted = z.toJSONSchema(registry, {
    target: "draft-2020-12",
    io: "output",
    unrepresentable: "any",
    uri: (id: string) => `#/components/schemas/${id}`,
  }).schemas as Record<string, Record<string, unknown>>;
  const components: Record<string, unknown> = {};
  for (const name of Object.keys(SCHEMAS)) {
    const json = { ...emitted[name] };
    delete json["$schema"];
    delete json["$id"];
    json["title"] ??= name;
    components[name] = json;
  }
  const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
  const staticGet = (summary: string, schema: string, description: string, params: Array<{ name: string; schema: unknown; description: string }> = []) => ({
    get: {
      summary,
      description,
      ...(params.length
        ? { parameters: params.map((p) => ({ name: p.name, in: "path", required: true, schema: p.schema, description: p.description })) }
        : {}),
      responses: {
        "200": { description: "The artefact.", content: { "application/json": { schema: ref(schema) } } },
        "404": { description: "Not generated (yet). The app must render a specific error state, never a blank page." },
      },
    },
  });
  return {
    openapi: "3.1.0",
    info: {
      title: "SagePlan static data contract",
      version: "0.1.0",
      description:
        "GENERATED by `npm run contract:openapi` from packages/shared. Do not edit by hand.\n\n" +
        "There is no runtime server. These paths are static JSON files emitted by the pipeline into /data and served by the web app from its own origin. " +
        "The web app never sends student data anywhere; the only requests it makes are GETs of these paths. " +
        "scripts/contract-test.sh validates the files on disk against these schemas.",
    },
    servers: [{ url: "http://localhost:{port}", description: "Vite dev server (FRONTEND_PORT from .env)", variables: { port: { default: "3000" } } }],
    paths: {
      [ARTEFACT_PATHS.manifest.path]: staticGet("Artefact manifest", "Manifest", "First request the app makes. Lists every artefact, its freshness and the terms available."),
      [ARTEFACT_PATHS.catalog.path]: staticGet("Course catalog", "CatalogArtefact", "Every Pomona course in the catalog year with its GE attributes. Stable; rebuilt per catalog year."),
      [ARTEFACT_PATHS.sections.path]: staticGet("Sections for one term", "SectionsArtefact", "Live per-term section data from Hyperschedule, rebuilt nightly. One file per term listed in manifest.upcomingTerms.", [
        { name: "term", schema: { type: "string", pattern: "^(FA|SP)\\d{4}$" }, description: 'Term code, e.g. "SP2027".' },
      ]),
      [ARTEFACT_PATHS.offeringHistory.path]: staticGet("Offering history", "OfferingHistoryArtefact", "Every term each course has run since ~2012. Powers the term ribbon."),
      [ARTEFACT_PATHS.program.path]: staticGet("Program (requirements as data)", "Program", "Hand-written, reviewed requirement set. general-education-2026 in P0; majors and minors later, same shape.", [
        { name: "programId", schema: { type: "string", pattern: "^[a-z0-9-]+$" }, description: "Program id from manifest.programs." },
      ]),
      [ARTEFACT_PATHS.externalCreditRules.path]: staticGet("External credit rules", "ExternalCreditRules", "AP / IB / A-Level / SAT-II thresholds -> credits and granted attributes."),
    },
    components: { schemas: components },
    "x-engine-contract": {
      description: "Pure functions exported by @sageplan/engine. Not HTTP. Documented in docs/API.md §Engine contract.",
      evaluate: "evaluate(plan: StudentPlan, programs: Program[], catalog: Course[]): Result[]",
      resolveExternalCredit: "resolveExternalCredit(input: ExternalCreditInput, rules: ExternalCreditRules): ExternalCredit",
    },
  };
}

export function renderOpenApiYaml(): string {
  return stringify(buildOpenApi(), { lineWidth: 0, aliasDuplicateObjects: false });
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const yamlText = renderOpenApiYaml();
  if (process.argv.includes("--check")) {
    let current = "";
    try { current = readFileSync(OUT, "utf8"); } catch { /* missing counts as stale */ }
    if (current !== yamlText) {
      console.error(`STALE: ${OUT} does not match the schemas. Run: npm run contract:openapi`);
      process.exit(1);
    }
    console.log(`openapi.yaml is current (${Object.keys(SCHEMAS).length} schemas)`);
  } else {
    writeFileSync(OUT, yamlText);
    console.log(`wrote ${OUT} (${yamlText.split("\n").length} lines, ${Object.keys(SCHEMAS).length} schemas)`);
  }
}
